// Real Google reviews of Alpha Dental Studio, copied verbatim from the Google-review widget on the clinic's
// own website (alphadentalstudios.com), as displayed in Sept–Oct 2024. Nothing is edited or invented.
// This is only a fallback: when GOOGLE_PLACES_API_KEY and the Place ID are set, live reviews replace it
// (see components/sections/GoogleReviews.tsx). Add newer reviews here by copying them from Google.
export type SnapshotReview = { name: string; date: string; rating: 5; text: string };

export const snapshotReviews: SnapshotReview[] = [
  { name: "sharmesh kumar", date: "2024-10-18", rating: 5, text: "I had an amazing experience at Alpha Dental Studio with Dr. Varshini for my scaling and polishing treatment, all under the expert supervision of Dr. Zeenath! From start to finish, Dr. Varshini was professional, gentle, and thorough. Her friendly approach and clear explanations made the whole process smooth and stress-free. The clinic’s modern vibe and the welcoming staff added to the overall great experience. My teeth feel super clean, and I’m thrilled with the results! If you're looking for exceptional dental care, I highly recommend Dr. Varshini and Dr. Zeenath’s team — they’re the best!" },
  { name: "Rumaysa", date: "2024-10-13", rating: 5, text: "I went to Alpha dental studio for my aligners & I was very satisfied with the experience I had at this clinic, the dentists are very empathetic & are knowledgeable about all the process & treatment in their fields.The clinic itself is very clean, calming & gives a peaceful effect which helps to calm ourselves.They explain the process of their treatments to patients & reassure them when they feel doubtful.Overall the experience was simply wonderful." },
  { name: "Dr. Mark Jittu", date: "2024-10-04", rating: 5, text: "I accompanied my mom to this dental clinic for her root canal treatment. The treatment provided was exceptional! 🙌 A big shoutout to the skilled team of dentists led by Dr. Zeenath, especially Dr. Diana, Dr. Varshini, and Dr. Anjali. 👍 If you're looking for a top-notch dental clinic, look no further! #DentistryAtItsBest #ThankfulPatient #HealthySmile 😊🦷" },
  { name: "Mark Jittu Vincent", date: "2024-10-04", rating: 5, text: "A colleague recommended this place to me because I have been experiencing persistent chewing problems. I scheduled an appointment with Dr. Diana, who was courteous and provided a clear explanation of malocclusion. Although the cost may appear high, the potential benefits make it a worthwhile investment. I also want to express my gratitude to Dr. Zeenath for bringing such qualified professionals like Dr Diana to her clinic. I highly recommend this clinic." },
  { name: "Beulaja Vincent", date: "2024-10-04", rating: 5, text: "I recently visited Alpha Dental Studio for a routine dental checkup. I was seen by Dr. Zeenath, who identified some alignment issues and referred me to Dr. Diana Ashok, a highly skilled orthodontist. She has developed a comprehensive treatment plan that I am excited to begin. I am confident that I will achieve excellent results and highly recommend Alpha Dental Studio for their expertise and professionalism." },
  { name: "GOKUL 23", date: "2024-10-02", rating: 5, text: "Excellent Service right from appointment till treatment completion in Alpha dental studio.It is a premium and serene clinic highly qualified Professors are available here for Dental Implant and Impacted molar teeth Extraction.Dr Aravind and Dr Zeenath did the great job without pain.My implant treatment completed on time and as per the treatment planThey charged me very reasonable rate as compared to other Clinics in metro cities and I know the charge and spent huge amount in a banglore for one Implant earlier. I think other treatments charge also reasonable here. Thank you Doctors. I have already recommended to my family and friends." },
  { name: "ponnurangan m", date: "2024-10-02", rating: 5, text: "Very good n excellent service providers.smart n patience doctor Dr zeenath and cool assistants.I felt happy with their treatment and hospitality.My smile improved a lot after the treatment . I did my front teeth veneers . They have excellent team of doctors who are expertise in their treatments. Complete treatment is in international standards. Best dental clinic in chennai.Thank you so much to the whole team. Very much recommended." },
  { name: "Duke Allwyn", date: "2024-10-01", rating: 5, text: "The care provided by Alpha dental studio is absolutely professional and outstanding.I being a patient of Dr.Zeenath I can say that she is friendly and she explains about the treatment understandably.The clinic environment is very hygienic and the staff is very kind.i underwent tooth colour fillings,implant and zirconia crowns. Thank you doctor. Highly recommended." },
  { name: "Priya Moorthy", date: "2024-10-01", rating: 5, text: "I wasn’t able to smile openly but with Dr zeenath and her Invisalign treatment suggestion , I underwent treatment with her . I am in the process of Invisalign journey.i am so happy i am getting the smile i wanted .Thoroughly satisfied and great follow up by the entire team ! Best Invisalign treatment in chennai with affordable cost." },
  { name: "Indhu Thangavel", date: "2024-09-30", rating: 5, text: "One of the best caring and affordable dental clinic in Chennai. Dr. Zeenath mam is kind and soft spoken person she treated us very kindly and explained everything in proper knowledgeable way. Me and my family members satisfied with their work. I have undegone rct and crowns. Highly recommended.🫰" },
];
