// The nine service areas listed on the clinic's current website, with the procedures it names for each.
export type Specialty = { n: string; title: string; blurb: string; items: string[]; image: string; alt: string; href: string };

export const specialties: Specialty[] = [
  { n: "01", title: "General dentistry", blurb: "Personalised care for everyday oral health, from check-ups to relief of tooth and jaw pain.", items: ["Examination & cleaning", "Fillings", "Tooth extractions", "TMJ & night guards"], image: "/images/procedure.jpg", alt: "Dentists performing a dental procedure", href: "/treatments#general" },
  { n: "02", title: "Cosmetic dentistry", blurb: "Shape and brighten your smile, from subtle changes to a complete makeover.", items: ["Teeth whitening", "Dental bonding", "Porcelain veneers", "Smile makeover"], image: "/images/clinic/cosmetic-shade.jpg", alt: "Smile next to a tooth shade guide", href: "/treatments#cosmetic" },
  { n: "03", title: "Orthodontics", blurb: "Straighter teeth and a better bite with braces, clear aligners and retainers.", items: ["Braces", "Invisalign clear aligners", "Retainers"], image: "/images/clinic/aligner.jpg", alt: "Person fitting a clear aligner", href: "/treatments#orthodontics" },
  { n: "04", title: "Endodontics", blurb: "Treatment for the inside of the tooth, to save teeth that are infected or damaged.", items: ["Root canal therapy", "Infection and abscess care", "Trauma care"], image: "/images/xray-lightbox.jpg", alt: "Dentist examining dental X-rays", href: "/treatments/root-canal-treatment" },
  { n: "05", title: "Periodontics", blurb: "Care for your gums and the structures that support your teeth.", items: ["Gum disease treatment", "Deep cleaning", "Bone grafting", "Implant placement"], image: "/images/clinic/smile-2.jpg", alt: "Close-up of a healthy smile", href: "/treatments/gum-treatment" },
  { n: "06", title: "Restorative dentistry", blurb: "Repair and replace worn, damaged or missing teeth.", items: ["Dental crowns", "Bridges", "Dentures", "Dental implants"], image: "/images/implant-model.jpg", alt: "Dental implant model with teeth", href: "/treatments/dental-crowns-bridges" },
  { n: "07", title: "Oral surgery", blurb: "Gentle, well-planned surgery with a patient-centred approach to recovery.", items: ["Wisdom tooth removal", "Sinus lifts", "Apicoectomy", "Ridge augmentation", "Corrective jaw surgery"], image: "/images/opg-xray.jpg", alt: "Panoramic X-ray of teeth and jaw", href: "/treatments/oral-maxillofacial-surgery" },
  { n: "08", title: "Sedation dentistry", blurb: "Oral conscious sedation, so you stay awake but deeply relaxed.", items: ["Anxiety and dental phobia", "Strong gag reflex", "Longer procedures"], image: "/images/clinic-chair.jpg", alt: "Calm dental treatment room", href: "/treatments/sedation-dentistry" },
  { n: "09", title: "Special needs dentistry", blurb: "Compassionate, individual care with open communication for patients and families.", items: ["Custom hygiene plans", "Gag reflex support", "Care coordination", "Emergency care"], image: "/images/clinic-room-alt.jpg", alt: "Calm dental consultation room", href: "/treatments/special-needs-dentistry" },
];
