import type { Doctor } from "./doctors";
import { treatmentGroups } from "./treatment-groups";

// Plain-English, conservative copy. Procedure lists come from the clinic's live service pages.
// `costFrom`/`costTo` are TODO (clinic to supply): the cost block is hidden while empty.
// `reviewedBy` only shows publicly once `reviewConfirmed` is true (the clinic must confirm the review actually happened).
export type Faq = { q: string; a: string };
export type Treatment = {
  slug: string;
  group: string;
  title: string; // short label
  h1: string;
  keyword: string;
  promise: string;
  intro: string;
  image: string; // id from content/images.json
  imageAlt: string;
  doctors: string[]; // doctor slugs
  signs: string[];
  steps: { title: string; body: string }[];
  visits: string;
  duration: string;
  benefits: string[];
  thingsToKnow: string[];
  faqs: Faq[];
  related: string[];
  costFrom?: number;
  costTo?: number;
  reviewedBy?: string;
  reviewConfirmed?: boolean;
  lastReviewed: string;
};

const T = (t: Omit<Treatment, "lastReviewed" | "reviewConfirmed">): Treatment => ({ ...t, lastReviewed: "2026-10-06", reviewConfirmed: false });

export const treatments: Treatment[] = [
  T({
    slug: "dental-check-up-cleaning", group: "general", title: "Check-up & cleaning",
    h1: "Dental check-up and cleaning in Chennai", keyword: "dental check-up and cleaning in Chennai",
    promise: "A calm, thorough examination and a professional clean, with a clear explanation of what we find.",
    intro: "A routine dental check-up and cleaning in Chennai is the simplest way to catch small problems before they become painful or expensive. At Alpha Dental Studio, your visit includes an oral examination, professional scaling and polishing, and a plain-language summary of your gum and tooth health.",
    image: "mirror-explorer", imageAlt: "Dental mirror and explorer used for a dental check-up and cleaning in Chennai",
    doctors: ["dr-varshini", "dr-archana"],
    signs: ["You haven't seen a dentist in the last 6–12 months", "Your gums bleed when you brush or floss", "You notice tartar, stains or bad breath that doesn't go away", "You want a baseline check before starting any other treatment", "Your teeth feel rough or sensitive to hot and cold"],
    steps: [
      { title: "History and examination", body: "We ask about your health, medicines and any concerns, then examine your teeth, gums and bite." },
      { title: "Digital imaging if needed", body: "Where it helps the diagnosis, we take digital X-rays, which use a lower radiation dose than traditional film." },
      { title: "Scaling and polishing", body: "Ultrasonic scaling removes plaque and tartar, followed by polishing to smooth the tooth surface." },
      { title: "Your plan", body: "We explain what we found and what, if anything, needs treatment, with options and costs before we start." },
    ],
    visits: "Usually one visit", duration: "30–45 minutes",
    benefits: ["Early detection of cavities and gum problems", "Fresher breath and a cleaner feel", "Removes stains that brushing cannot", "A clear record of your oral health"],
    thingsToKnow: ["Gums may bleed slightly if you have gum inflammation, and this usually settles within days of regular cleaning", "Teeth can feel sensitive for a day or two after scaling", "Cleaning does not whiten teeth beyond removing surface stains", "Most people benefit from a check-up every six months, though your dentist may advise differently"],
    faqs: [
      { q: "How often should I get my teeth cleaned?", a: "Many people do well with a check-up and cleaning every six months. If you have gum disease or other risk factors, your dentist may suggest more frequent visits." },
      { q: "Does scaling damage teeth?", a: "No. Professional scaling removes plaque and tartar from the surface. Gaps that seem to appear afterwards were usually hidden by tartar before." },
      { q: "Is teeth cleaning painful?", a: "Most patients feel only mild vibration or sensitivity. If your teeth are very sensitive, tell us and we can adjust the approach." },
      { q: "Will cleaning make my teeth whiter?", a: "It removes surface stains, so teeth often look brighter. For a shade change, you would need a whitening treatment." },
      { q: "What is the difference between a check-up and a deep cleaning?", a: "A routine clean addresses plaque and tartar above the gum line. A deep cleaning treats the roots below the gum line and is advised when there is gum disease." },
    ],
    related: ["gum-treatment", "teeth-whitening", "kids-dentistry"], reviewedBy: "dr-varshini",
  }),
  T({
    slug: "tooth-extraction", group: "general", title: "Tooth extraction",
    h1: "Tooth extraction in Chennai", keyword: "tooth extraction in Chennai",
    promise: "Gentle removal of teeth that cannot be saved, with a plan for replacing them if you wish.",
    intro: "Tooth extraction in Chennai is sometimes the right choice when a tooth is badly decayed, fractured, infected or crowding other teeth. Our team plans each extraction carefully, numbs the area fully and talks you through recovery. Sedation is available for anxious patients.",
    image: "procedure", imageAlt: "Dentists performing a tooth extraction procedure at a dental clinic in Chennai",
    doctors: ["dr-aravind-sai", "dr-archana"],
    signs: ["A tooth is too damaged to be repaired", "You have repeated infection or abscess around a tooth", "A tooth is loose because of advanced gum disease", "A baby tooth has not fallen out on time", "Extraction is advised before braces or dentures"],
    steps: [
      { title: "Examination and X-ray", body: "We assess the tooth, the surrounding bone and your medical history." },
      { title: "Local anaesthesia", body: "The area is numbed so you feel pressure but not sharp pain. Sedation can be arranged if you are anxious." },
      { title: "Removal", body: "The tooth is loosened and removed with care for the surrounding bone and gum." },
      { title: "Aftercare and replacement plan", body: "You receive written aftercare, and we discuss options such as an implant, bridge or denture." },
    ],
    visits: "Usually one visit, plus a short follow-up if needed", duration: "20–60 minutes depending on the tooth",
    benefits: ["Relief from pain and infection", "Protects neighbouring teeth and gums", "Makes room for orthodontic treatment when advised", "Opens the way to a proper replacement"],
    thingsToKnow: ["Bleeding, swelling and tenderness are normal for a few days", "Avoid rinsing hard, spitting, smoking or using a straw for the first 24 hours", "Dry socket is uncommon but can happen; call us if pain gets worse after day 2–3", "Tell us about blood thinners, diabetes or any heart condition beforehand"],
    faqs: [
      { q: "Is tooth extraction painful?", a: "The area is numbed first, so you should feel pressure rather than pain. Some soreness afterwards is normal and usually managed with simple pain relief as advised." },
      { q: "How long does it take to heal?", a: "The gum usually settles in one to two weeks. The bone underneath takes longer to remodel." },
      { q: "Do I need to replace an extracted tooth?", a: "Often yes. A gap can let neighbouring teeth drift and can affect chewing. Options include implants, bridges and dentures." },
      { q: "Can I eat after an extraction?", a: "Yes, once the numbness wears off. Choose soft, cool food and chew on the other side for the first day or two." },
      { q: "Can extraction be done under sedation?", a: "Yes. We offer oral conscious sedation for patients who are very anxious or need a more complex procedure." },
    ],
    related: ["dental-implants", "dentures", "sedation-dentistry"], reviewedBy: "dr-aravind-sai",
  }),
  T({
    slug: "kids-dentistry", group: "general", title: "Kids dentistry",
    h1: "Kids dentist in R.A. Puram", keyword: "kids dentist in R.A. Puram",
    promise: "A friendly first dental experience, so children grow up comfortable at the dentist.",
    intro: "Looking for a kids dentist in R.A. Puram? Our team keeps children's visits short, gentle and explained in simple words. We focus on prevention, early checks and building trust, because a good first experience shapes how a child feels about dental care for years.",
    image: "kids-exam", imageAlt: "Dentist examining a young boy's teeth at a kids dentist in R.A. Puram",
    doctors: ["dr-varshini"],
    signs: ["Your child's first teeth have appeared", "You see brown or white spots on teeth", "Your child complains of tooth pain or avoids chewing on one side", "Thumb-sucking or mouth-breathing continues beyond the toddler years", "It is time for a routine six-monthly check-up"],
    steps: [
      { title: "A relaxed introduction", body: "We let your child meet the team and see the chair before anything is done." },
      { title: "Gentle examination", body: "We check teeth, gums, bite and jaw growth, using simple words and demonstrations." },
      { title: "Cleaning and prevention", body: "Depending on age, this may include cleaning, fluoride advice and fissure sealants where appropriate." },
      { title: "Advice for parents", body: "You get practical guidance on brushing, diet, and habits such as thumb-sucking." },
    ],
    visits: "Check-ups every six months", duration: "20–30 minutes",
    benefits: ["Early spotting of cavities and bite problems", "Builds dental confidence", "Prevention advice tailored to age", "Guidance on habits that affect jaw growth"],
    thingsToKnow: ["Baby teeth matter: they hold space for adult teeth and help with speech and chewing", "Frequent sugary snacks and sweet drinks raise cavity risk", "A child may need several short visits before longer treatment", "Bring any questions about bottle use, pacifiers and teething"],
    faqs: [
      { q: "When should my child first see a dentist?", a: "A common guideline is by the first birthday or when the first tooth appears. Early visits are mostly about prevention and getting comfortable." },
      { q: "Do baby teeth need fillings?", a: "Sometimes. Untreated decay in baby teeth can cause pain and infection and affect the adult teeth underneath." },
      { q: "How can I help my child feel less nervous?", a: "Stay calm, avoid words like 'pain' or 'injection', and let us guide the conversation. Short, positive visits work best." },
      { q: "Are dental X-rays safe for children?", a: "They are used only when needed. Digital X-rays use a low dose, and we use them when the benefit outweighs the small exposure." },
      { q: "Should my child use fluoride toothpaste?", a: "Usually yes, in an amount suited to their age. We can advise on the right quantity for your child." },
    ],
    related: ["dental-check-up-cleaning", "braces", "sedation-dentistry"], reviewedBy: "dr-varshini",
  }),
  T({
    slug: "root-canal-treatment", group: "restorative", title: "Root canal treatment",
    h1: "Root canal treatment in Chennai", keyword: "root canal treatment in Chennai",
    promise: "Save an infected or badly damaged tooth, with comfort and clear explanations throughout.",
    intro: "Root canal treatment in Chennai is how endodontists save a tooth whose inner pulp is infected or damaged. At Alpha Dental Studio, root canals are handled by our endodontists, using digital imaging and careful numbing so the treatment is as comfortable as possible.",
    image: "xray-lightbox", imageAlt: "Dentist examining dental X-rays before root canal treatment in Chennai",
    doctors: ["dr-mahalakshmi", "dr-anjali-sankar"],
    signs: ["Severe or throbbing toothache, especially at night", "Lingering sensitivity to hot or cold", "A swollen, tender gum or a pimple-like bump near a tooth", "A tooth that has darkened after an injury", "Deep decay or a cracked tooth reaching the nerve"],
    steps: [
      { title: "Diagnosis", body: "We examine the tooth and take an X-ray to confirm the extent of infection." },
      { title: "Numbing and access", body: "The area is anaesthetised, and a small opening is made to reach the pulp." },
      { title: "Cleaning and shaping", body: "The infected tissue is removed and the canals are cleaned and shaped." },
      { title: "Sealing and restoration", body: "Canals are filled and sealed. The tooth is then protected, usually with a crown." },
    ],
    visits: "1–3 visits depending on the tooth and infection", duration: "45–90 minutes per visit",
    benefits: ["Keeps your natural tooth", "Relieves the pain caused by infection", "Avoids the gap and cost of extraction and replacement", "Lets you chew normally again"],
    thingsToKnow: ["Mild tenderness for a few days is common", "A crown is usually advised to protect a treated back tooth", "Avoid chewing hard food on the tooth until it is restored", "Very damaged teeth may not be savable, and we will tell you honestly if so"],
    faqs: [
      { q: "Is root canal treatment painful?", a: "The tooth is numbed before we begin, so the procedure itself should not be painful. The pain people associate with root canals usually comes from the infection, not the treatment." },
      { q: "How many visits does a root canal take?", a: "Many teeth are completed in one or two visits. Infected or complex teeth may need more." },
      { q: "Do I need a crown after a root canal?", a: "Often yes, particularly for back teeth, because a treated tooth can be more brittle. Your dentist will advise after assessment." },
      { q: "What happens if I delay a root canal?", a: "Infection can spread to the bone and gums, causing swelling and sometimes the loss of the tooth." },
      { q: "Is extraction better than a root canal?", a: "Saving your own tooth is usually preferred when it can be restored. If the tooth cannot be saved, we will discuss replacement options." },
      { q: "How long does a treated tooth last?", a: "With good restoration and care, many root-canal-treated teeth last for many years. Longevity varies from person to person." },
    ],
    related: ["dental-crowns-bridges", "laser-dentistry", "tooth-extraction"], reviewedBy: "dr-mahalakshmi",
  }),
  T({
    slug: "dental-crowns-bridges", group: "restorative", title: "Crowns & bridges",
    h1: "Dental crowns and bridges in Chennai", keyword: "dental crowns and bridges in Chennai",
    promise: "Strong, natural-looking restorations that rebuild damaged teeth and close gaps.",
    intro: "Dental crowns and bridges in Chennai repair teeth that are broken, heavily filled or missing. A crown covers a damaged tooth; a bridge replaces one or more missing teeth by anchoring to neighbouring teeth. We choose materials and shade with you, and use digital scanning where suitable for a precise fit.",
    image: "intraoral-scanner", imageAlt: "Dentist using an intraoral scanner for dental crowns and bridges in Chennai",
    doctors: ["dr-anjali-sankar"],
    signs: ["A tooth is cracked, worn or heavily filled", "A tooth has had root canal treatment", "You have a gap from a missing tooth", "An old crown is loose or discoloured", "You want to improve the shape or shade of a tooth"],
    steps: [
      { title: "Assessment", body: "We examine the tooth, check your bite and discuss material and shade options." },
      { title: "Preparation", body: "The tooth is numbed and shaped to receive the crown or to anchor a bridge." },
      { title: "Impression or scan", body: "A digital scan or impression records the exact shape for the laboratory." },
      { title: "Temporary, then fitting", body: "A temporary protects the tooth until the final restoration is checked, adjusted and cemented." },
    ],
    visits: "Usually 2 visits", duration: "45–60 minutes per visit",
    benefits: ["Restores strength and chewing function", "Natural shape and colour match", "Closes gaps and protects neighbouring teeth", "Long-lasting with good care"],
    thingsToKnow: ["Teeth may feel sensitive to temperature for a short time", "Brushing and flossing around the restoration is essential", "Bridges need healthy anchor teeth", "Crowns can chip if you bite very hard objects"],
    faqs: [
      { q: "How long do dental crowns last?", a: "Many crowns last ten years or more with good hygiene and regular check-ups, though this varies by material, bite and habits." },
      { q: "What is the difference between a crown and a bridge?", a: "A crown covers one tooth. A bridge replaces missing teeth by joining crowns on neighbouring teeth across the gap." },
      { q: "Are crowns painful?", a: "The tooth is numbed during preparation. Mild sensitivity afterwards is common and usually settles." },
      { q: "Which crown material is best?", a: "It depends on the tooth's position, your bite and appearance goals. We explain the options for your case." },
      { q: "Should I get a bridge or an implant?", a: "Both can replace a missing tooth. An implant does not rely on neighbouring teeth; a bridge is faster and avoids surgery. We will help you compare." },
    ],
    related: ["dental-implants", "root-canal-treatment", "dentures"], reviewedBy: "dr-anjali-sankar",
  }),
  T({
    slug: "dentures", group: "restorative", title: "Dentures",
    h1: "Dentures in Chennai", keyword: "dentures in Chennai",
    promise: "Comfortable, well-fitted dentures that help you eat, speak and smile with confidence.",
    intro: "Dentures in Chennai replace missing teeth with removable teeth that restore chewing and appearance. Whether you need a few teeth or a full set replaced, our team measures carefully, explains your options and adjusts the fit until it feels comfortable.",
    image: "denture", imageAlt: "Hand holding a denture, available as dentures in Chennai",
    doctors: ["dr-aravind-sai"],
    signs: ["You have lost several or all teeth", "Eating or speaking has become difficult", "Existing dentures are loose or sore", "Teeth cannot be saved by other treatment", "You want a non-surgical replacement option"],
    steps: [
      { title: "Consultation", body: "We discuss your needs, examine your mouth and explain partial, complete and implant-supported options." },
      { title: "Impressions and measurements", body: "Accurate records of your gums and bite are taken." },
      { title: "Try-in", body: "You see the teeth set in wax, so shape, shade and fit can be adjusted before the final version." },
      { title: "Fitting and review", body: "We fit the denture, check comfort and bite, and review it after a few days." },
    ],
    visits: "Typically 3–5 visits", duration: "30–45 minutes per visit",
    benefits: ["Restores chewing and speech", "Improves facial support and appearance", "Non-surgical option", "Can be adjusted over time"],
    thingsToKnow: ["New dentures take a few weeks to get used to", "Sore spots can happen and are easily adjusted", "Remove and clean them daily, and leave them out at night as advised", "Gums and jaw change shape over time, so dentures may need relining"],
    faqs: [
      { q: "How long does it take to get used to dentures?", a: "Most people adapt over a few weeks. Speaking and eating get easier with practice." },
      { q: "How do I clean my dentures?", a: "Brush them daily with a soft brush and mild soap or a denture cleaner, and rinse after meals." },
      { q: "Can dentures be made more stable?", a: "Yes. Dentures can be supported by dental implants for extra stability. Ask us whether you are a candidate." },
      { q: "How long do dentures last?", a: "Typically several years, though they may need relining or replacing as your mouth changes." },
      { q: "Can I sleep with my dentures in?", a: "It is generally advised to remove them at night to rest your gums, unless your dentist says otherwise." },
    ],
    related: ["dental-implants", "dental-crowns-bridges", "tooth-extraction"], reviewedBy: "dr-aravind-sai",
  }),
  T({
    slug: "dental-implants", group: "implants-surgery", title: "Dental implants",
    h1: "Dental implants in Chennai", keyword: "dental implants in Chennai",
    promise: "A fixed, natural-feeling replacement for missing teeth, planned carefully from start to finish.",
    intro: "Dental implants in Chennai are titanium posts placed in the jawbone to hold a crown, bridge or denture. They replace the tooth root as well as the visible tooth. Our implantologist plans each case with imaging, explains timelines and healing, and coordinates the final restoration.",
    image: "implant-crown", imageAlt: "Gloved hand holding a dental implant and crown, dental implants in Chennai",
    doctors: ["dr-aravind-sai"],
    signs: ["You are missing one or more teeth", "You want a fixed option without grinding down neighbouring teeth", "Your dentures feel loose", "You have lost a tooth and want to protect your jawbone", "You are in good general health and have enough bone, or can have it built up"],
    steps: [
      { title: "Assessment and 3D imaging", body: "We examine your mouth and use imaging to check bone and plan implant position." },
      { title: "Implant placement", body: "Under local anaesthesia (with sedation if suitable), the implant is placed in the bone." },
      { title: "Healing", body: "The implant fuses with the bone over several weeks to months, depending on the case." },
      { title: "Crown fitting", body: "Once healed, a custom crown, bridge or denture is attached and your bite is checked." },
    ],
    visits: "Several visits across 3–6 months, sometimes longer", duration: "Placement visit about 1 hour per implant",
    benefits: ["Feels and functions like a natural tooth", "Does not rely on neighbouring teeth", "Helps preserve jawbone", "Can last many years with good care"],
    thingsToKnow: ["Some swelling and tenderness are normal for a few days after surgery", "Smoking and uncontrolled diabetes raise the risk of failure", "Bone grafting or a sinus lift may be needed first", "Regular cleaning and check-ups are essential to protect gums around the implant"],
    faqs: [
      { q: "How long do dental implants last?", a: "With good oral hygiene and regular check-ups, many implants last for many years, often decades. Results vary with health, habits and gum care." },
      { q: "Is the implant procedure painful?", a: "The area is numbed, so you should not feel pain during surgery. Some discomfort afterwards is expected and can be managed." },
      { q: "Am I a candidate for dental implants?", a: "Most healthy adults with enough bone can have them. We assess your health, gums and bone before recommending." },
      { q: "How long does the whole process take?", a: "Typically several months, because the implant needs time to fuse with the bone. Some cases are faster." },
      { q: "What is the difference between an implant and a bridge?", a: "A bridge relies on neighbouring teeth for support. An implant stands on its own in the jawbone." },
      { q: "Can I get an implant if I have gum disease?", a: "Gum disease should be treated and controlled first. Our periodontist can help prepare the area." },
    ],
    related: ["dental-crowns-bridges", "dentures", "gum-treatment"], reviewedBy: "dr-aravind-sai",
  }),
  T({
    slug: "wisdom-tooth-removal", group: "implants-surgery", title: "Wisdom tooth removal",
    h1: "Wisdom tooth removal in Chennai", keyword: "wisdom tooth removal in Chennai",
    promise: "Careful surgical removal of impacted or problem wisdom teeth by an oral surgeon.",
    intro: "Wisdom tooth removal in Chennai is advised when third molars are impacted, decayed, repeatedly infected or pushing on other teeth. Our oral and maxillofacial surgeon plans each case with imaging, so you know what to expect before, during and after the procedure.",
    image: "opg-xray", imageAlt: "Panoramic dental X-ray used to plan wisdom tooth removal in Chennai",
    doctors: ["dr-aravind-sai"],
    signs: ["Pain or swelling at the back of the jaw", "Repeated gum infection around a partly erupted wisdom tooth", "Decay in a wisdom tooth or the tooth in front of it", "Crowding or pressure on your other teeth", "A wisdom tooth stuck under the gum or bone, seen on X-ray"],
    steps: [
      { title: "Consultation and X-ray", body: "A panoramic X-ray shows the position of the tooth and nearby nerves." },
      { title: "Anaesthesia", body: "Local anaesthesia, with oral sedation as an option, keeps you comfortable." },
      { title: "Removal", body: "The tooth is removed, sometimes in sections, and the gum is stitched if needed." },
      { title: "Recovery guidance", body: "You get written instructions, medicines as prescribed and a follow-up if required." },
    ],
    visits: "Usually 1 visit plus a review", duration: "30–60 minutes",
    benefits: ["Relief from pain and recurrent infection", "Protects neighbouring teeth", "Prevents future problems from impaction", "Planned with imaging for safety"],
    thingsToKnow: ["Swelling peaks around day 2–3 and settles over about a week", "Eat soft food and avoid strenuous activity for a few days", "Temporary numbness in the lip or tongue is uncommon but possible and is discussed beforehand", "Not every wisdom tooth needs removal"],
    faqs: [
      { q: "Do all wisdom teeth need to be removed?", a: "No. Those that are healthy, fully erupted and easy to clean can stay. We recommend removal when there is a problem or a clear risk." },
      { q: "Is wisdom tooth removal painful?", a: "The area is numbed, so you should feel pressure but not pain. Some soreness afterwards is normal." },
      { q: "How long is recovery?", a: "Most people feel much better within a week. Full gum healing takes longer." },
      { q: "Can I go to work the next day?", a: "Many people rest for a day or two, depending on the complexity and how they feel." },
      { q: "Can wisdom teeth be removed under sedation?", a: "Yes. Oral conscious sedation is available for anxious patients or more involved cases." },
    ],
    related: ["tooth-extraction", "oral-maxillofacial-surgery", "sedation-dentistry"], reviewedBy: "dr-aravind-sai",
  }),
  T({
    slug: "oral-maxillofacial-surgery", group: "implants-surgery", title: "Oral & maxillofacial surgery",
    h1: "Oral and maxillofacial surgeon in Chennai", keyword: "oral and maxillofacial surgeon in Chennai",
    promise: "Gentle, well-planned surgery for the teeth, jaws and supporting bone.",
    intro: "Looking for an oral and maxillofacial surgeon in Chennai? Our surgeon performs procedures from simple extractions to implant-related bone work, with an emphasis on clear communication, thorough planning and comfortable recovery.",
    image: "opg-xray", imageAlt: "Panoramic X-ray of teeth and jaw for oral and maxillofacial surgery in Chennai",
    doctors: ["dr-aravind-sai"],
    signs: ["You need a wisdom tooth or complicated tooth removed", "You need bone or sinus work before dental implants", "A root-tip infection has not cleared after earlier treatment", "You have a jaw alignment or structural concern", "You have been referred for surgical assessment"],
    steps: [
      { title: "Consultation and imaging", body: "We review your history and use imaging to understand the area." },
      { title: "Treatment planning", body: "We explain the procedure, risks, alternatives and recovery in plain words." },
      { title: "Procedure", body: "Surgery is performed with local anaesthesia or sedation, depending on the case." },
      { title: "Recovery and review", body: "We provide aftercare instructions and review healing." },
    ],
    visits: "Varies by procedure", duration: "30 minutes to a couple of hours",
    benefits: ["Specialist care for complex cases", "Planned with imaging", "Comfort-focused approach", "Coordinated with implant and restorative care"],
    thingsToKnow: ["Procedures offered include wisdom tooth and tooth extractions, sinus lifts, apicoectomy, bone grafting, ridge augmentation and corrective jaw surgery", "Swelling and tenderness are expected after surgery", "Complex jaw or cleft procedures need specific planning and may involve a wider team", "We will tell you if a case should be referred"],
    faqs: [
      { q: "What does an oral and maxillofacial surgeon do?", a: "They treat conditions of the teeth, jaws and supporting structures surgically, from complex extractions to bone grafting and jaw procedures." },
      { q: "What is an apicoectomy?", a: "It is a minor surgery that removes the tip of a tooth root and cleans the infected area when a root canal alone has not resolved the problem." },
      { q: "What is bone grafting?", a: "It adds bone to areas that have lost volume, often to create a stable base for a dental implant." },
      { q: "Will I be put to sleep?", a: "Most procedures here use local anaesthesia, with oral conscious sedation available. We discuss the right option for you." },
      { q: "How do I prepare for oral surgery?", a: "Share your medical history and medicines, follow any fasting instructions we give, and arrange for someone to accompany you if sedated." },
    ],
    related: ["dental-implants", "wisdom-tooth-removal", "tmj-jaw-pain"], reviewedBy: "dr-aravind-sai",
  }),
  T({
    slug: "braces", group: "orthodontics", title: "Braces",
    h1: "Braces treatment in Chennai", keyword: "braces treatment in Chennai",
    promise: "Straighter teeth and a better bite, planned by orthodontists.",
    intro: "Braces treatment in Chennai corrects crooked teeth, gaps and bite problems. Our orthodontists assess your teeth and jaws, explain your options, and plan treatment that improves both how your teeth look and how they work. Properly aligned teeth are also easier to clean.",
    image: "braces", imageAlt: "Close-up of teeth with metal braces, braces treatment in Chennai",
    doctors: ["dr-deena-nancy", "dr-diana-ashok"],
    signs: ["Crowded or crooked teeth", "Gaps between teeth", "An overbite, underbite or crossbite", "Difficulty cleaning between teeth", "Jaw or bite discomfort linked to misalignment"],
    steps: [
      { title: "Orthodontic assessment", body: "We examine your teeth and jaws, take records and discuss goals." },
      { title: "Treatment plan", body: "You see the proposed approach, expected duration and options such as metal braces or aligners." },
      { title: "Fitting", body: "Braces are bonded to the teeth and you learn how to clean around them." },
      { title: "Regular adjustments", body: "Visits every few weeks gradually move teeth into position." },
      { title: "Retention", body: "Retainers hold the result after braces come off." },
    ],
    visits: "Monthly adjustment visits", duration: "Often 12–24 months, depending on the case",
    benefits: ["Easier cleaning of properly aligned teeth", "Reduced risk of decay and gum disease", "Improved bite function and reduced tooth wear", "Can ease some jaw discomfort linked to misalignment", "Greater confidence in your smile"],
    thingsToKnow: ["Teeth can feel sore for a few days after each adjustment", "Brush carefully and avoid sticky or very hard foods", "Retainers must be worn as advised or teeth can shift back", "Missed appointments extend treatment time"],
    faqs: [
      { q: "How long does it take to straighten teeth with braces?", a: "Often one to two years, but it depends on your case. We give an estimate after assessment." },
      { q: "Are braces painful?", a: "Teeth are sore for a few days after fitting and adjustments. Most people manage this with simple measures." },
      { q: "What is the ideal age for braces?", a: "Braces can work at many ages, including adulthood. Early assessment in childhood helps us time treatment." },
      { q: "Can adults get braces?", a: "Yes. Many adults have orthodontic treatment, and clear options may be available." },
      { q: "Invisalign vs braces: which should I choose?", a: "Aligners are removable and less visible; braces are fixed and suit a wide range of cases. Your orthodontist will recommend based on your teeth." },
      { q: "Do I have to wear a retainer?", a: "Yes. Retainers keep teeth in their new position, and we explain how long to wear them." },
    ],
    related: ["invisalign-clear-aligners", "kids-dentistry", "dental-check-up-cleaning"], reviewedBy: "dr-deena-nancy",
  }),
  T({
    slug: "invisalign-clear-aligners", group: "orthodontics", title: "Invisalign clear aligners",
    h1: "Invisalign in Chennai", keyword: "Invisalign in Chennai",
    promise: "Near-invisible, removable aligners planned digitally by our Invisalign providers.",
    intro: "Invisalign in Chennai offers a discreet way to straighten teeth with a series of clear, removable aligners. Alpha Dental Studio has Invisalign providers on the team who plan your tooth movement digitally and monitor your progress throughout.",
    image: "aligner", imageAlt: "Person fitting a clear aligner over their teeth, Invisalign in Chennai",
    doctors: ["dr-s-zeenath", "dr-deena-nancy"],
    signs: ["Mild to moderate crowding or spacing", "You want a less visible alternative to braces", "You are an adult who prefers removable treatment", "You need to eat and clean teeth without brackets", "You can commit to wearing aligners most of the day"],
    steps: [
      { title: "Consultation and scan", body: "We assess suitability and take a digital scan of your teeth." },
      { title: "Digital treatment plan", body: "You see a preview of the planned tooth movement before starting." },
      { title: "Wearing your aligners", body: "You wear each set for the time advised, usually around 20–22 hours a day, and switch to the next." },
      { title: "Check-ups", body: "Regular reviews make sure teeth are moving as planned." },
      { title: "Retainers", body: "After treatment, retainers help keep the result." },
    ],
    visits: "Reviews every 6–8 weeks, depending on the plan", duration: "Often 6–18 months, depending on the case",
    benefits: ["Discreet appearance", "Removable for eating and cleaning", "Digital planning with a preview of the plan", "No brackets or wires"],
    thingsToKnow: ["Results depend on wearing the aligners as directed", "Not every case suits aligners; complex bites may need braces", "Remove aligners to eat and drink anything other than water", "You may need small attachments on teeth and mild discomfort when switching sets"],
    faqs: [
      { q: "Invisalign vs braces cost in Chennai: which is cheaper?", a: "Costs depend on the complexity of your case and the duration of treatment. Aligners are often priced higher than metal braces, and we give you an exact figure after examination." },
      { q: "Is Invisalign painful?", a: "You may feel pressure or tenderness for a few days when switching to a new set. It usually settles quickly." },
      { q: "How long do I need to wear Invisalign each day?", a: "Usually 20–22 hours a day, removing them only to eat, drink and clean." },
      { q: "Can Invisalign fix all problems?", a: "Many mild to moderate cases, but not all. We tell you honestly if braces would suit you better." },
      { q: "Will I need a retainer afterwards?", a: "Yes. Retainers help prevent teeth moving back." },
    ],
    related: ["braces", "teeth-whitening", "smile-makeover"], reviewedBy: "dr-deena-nancy",
  }),
  T({
    slug: "gum-treatment", group: "gums", title: "Gum treatment",
    h1: "Gum disease treatment in Chennai", keyword: "gum disease treatment in Chennai",
    promise: "Specialist care for bleeding, swollen or receding gums, from deep cleaning to advanced periodontal procedures.",
    intro: "Gum disease treatment in Chennai starts with an accurate diagnosis. Our periodontist treats gingivitis and periodontitis, offers deep cleaning, and manages bone loss with procedures such as bone grafting where needed. Healthy gums are the foundation for healthy teeth and for successful implants.",
    image: "procedure", imageAlt: "Dentists performing a gum treatment procedure, gum disease treatment in Chennai",
    doctors: ["dr-akshaya"],
    signs: ["Gums that bleed when brushing or flossing", "Red, swollen or tender gums", "Persistent bad breath", "Gums pulling away from teeth or teeth looking longer", "Loose teeth or changes in your bite"],
    steps: [
      { title: "Periodontal examination", body: "We measure the depth of the spaces around your teeth and check for bone loss." },
      { title: "Deep cleaning", body: "Scaling and root planing remove plaque and tartar beneath the gum line." },
      { title: "Review", body: "We check how your gums have responded and plan further treatment if needed." },
      { title: "Maintenance", body: "Regular professional cleanings and home care keep the disease under control." },
    ],
    visits: "Several visits", duration: "30–60 minutes per visit",
    benefits: ["Stops bleeding and inflammation", "Helps keep your natural teeth", "Reduces bad breath", "Supports successful implant treatment"],
    thingsToKnow: ["Gum disease is controlled rather than cured, so ongoing care matters", "Smoking and diabetes make gum disease harder to manage", "Gums can feel tender after deep cleaning", "Advanced cases may need surgical treatment or grafting"],
    faqs: [
      { q: "Why do my gums bleed when I brush?", a: "Bleeding is a common sign of gum inflammation caused by plaque. It usually improves with professional cleaning and good home care, but persistent bleeding should be checked." },
      { q: "Can gum disease be cured?", a: "Early gum disease can often be reversed. Advanced gum disease can be controlled but not fully reversed, so ongoing care is key." },
      { q: "When should I see a periodontist?", a: "If you have persistent bleeding, gum recession, loose teeth or pockets around teeth, a periodontist can assess and treat them." },
      { q: "Is deep cleaning painful?", a: "The area is usually numbed, so you should be comfortable. Tenderness afterwards is normal." },
      { q: "Does gum disease affect general health?", a: "Gum disease has been linked with conditions such as diabetes, so keeping your gums healthy supports overall health." },
    ],
    related: ["laser-dentistry", "dental-implants", "dental-check-up-cleaning"], reviewedBy: "dr-akshaya",
  }),
  T({
    slug: "laser-dentistry", group: "gums", title: "Laser dentistry",
    h1: "Laser dentistry in Chennai", keyword: "laser dentistry in Chennai",
    promise: "Gentle, precise soft-tissue treatment with advanced dental lasers.",
    intro: "Laser dentistry in Chennai uses focused light energy to treat soft tissues with precision. At Alpha Dental Studio, our team includes clinicians trained in laser dentistry, and lasers may be used for certain gum procedures and soft-tissue treatments where they suit the case.",
    image: "clinic-chair", imageAlt: "Bright dental treatment room where laser dentistry in Chennai is performed",
    doctors: ["dr-s-zeenath", "dr-mahalakshmi", "dr-arulmozhi"],
    signs: ["Gum contouring or reshaping is advised", "A soft-tissue problem needs a precise, minimally invasive approach", "You are anxious about drills and needles", "You want a gentler option where clinically suitable", "Your dentist has recommended laser for a specific procedure"],
    steps: [
      { title: "Assessment", body: "We confirm whether laser is a suitable option for your condition." },
      { title: "Preparation", body: "Eye protection is provided and, if needed, the area is numbed." },
      { title: "Treatment", body: "The laser is used with precision on the targeted tissue." },
      { title: "Aftercare", body: "We explain simple care and review healing." },
    ],
    visits: "Often a single visit per area", duration: "15–45 minutes",
    benefits: ["Precise treatment of soft tissue", "May reduce the need for stitches in some procedures", "Often comfortable, sometimes with less anaesthetic", "Can support faster, cleaner healing in suitable cases"],
    thingsToKnow: ["Lasers are not suitable for every procedure", "Some treatments still need conventional techniques", "Mild soreness can occur as the area heals", "Results depend on the condition being treated"],
    faqs: [
      { q: "Is laser dentistry painful?", a: "Many laser procedures are comfortable, and some need little or no anaesthetic. We will tell you what to expect for your treatment." },
      { q: "What can lasers treat in dentistry?", a: "Common uses include gum contouring and some soft-tissue procedures. Suitability depends on your case." },
      { q: "Is laser dentistry safe?", a: "When used by trained clinicians with proper protection, it is a recognised option for suitable procedures." },
      { q: "Does laser replace the dental drill?", a: "Not entirely. Lasers suit some soft-tissue work, while many procedures still use conventional instruments." },
      { q: "How soon will I heal?", a: "Healing varies by procedure. We give specific guidance after treatment." },
    ],
    related: ["gum-treatment", "smile-makeover", "root-canal-treatment"], reviewedBy: "dr-mahalakshmi",
  }),
  T({
    slug: "teeth-whitening", group: "cosmetic", title: "Teeth whitening",
    h1: "Teeth whitening in Chennai", keyword: "teeth whitening in Chennai",
    promise: "A brighter smile, done safely under professional supervision.",
    intro: "Teeth whitening in Chennai lightens stains and discolouration caused by tea, coffee, ageing and other everyday habits. At Alpha Dental Studio, whitening starts with an examination so we know your teeth and gums are suitable, and you get realistic expectations for the shade change.",
    image: "white-smile", imageAlt: "Close-up of a smile with white teeth after teeth whitening in Chennai",
    doctors: ["dr-s-zeenath"],
    signs: ["Your teeth have yellowed or stained over time", "You drink a lot of tea or coffee, or smoke", "You want a brighter smile before an event", "Your teeth are healthy with no active decay or gum disease", "You have had cleaning recently and still want a shade change"],
    steps: [
      { title: "Examination", body: "We check for decay, gum problems and sensitivity before whitening." },
      { title: "Cleaning", body: "A professional clean removes surface stains for a better result." },
      { title: "Whitening", body: "A professional whitening product is applied, with your gums protected." },
      { title: "Aftercare", body: "We advise on avoiding stain-causing food and drink for the first couple of days." },
    ],
    visits: "Usually one visit, sometimes more", duration: "About 60 minutes",
    benefits: ["Lighter shade of natural teeth", "Supervised, so your gums are protected", "Quick, with visible results", "Can be combined with other cosmetic treatment"],
    thingsToKnow: ["Temporary sensitivity is common", "Whitening does not change the colour of crowns, veneers or fillings", "Results vary and fade over time, depending on habits", "Treat decay and gum disease before whitening"],
    faqs: [
      { q: "Is teeth whitening safe?", a: "When done under professional supervision on healthy teeth, whitening is generally safe. Temporary sensitivity can occur." },
      { q: "How long do whitening results last?", a: "It varies by person and habits such as tea, coffee and smoking. Touch-ups can help maintain the shade." },
      { q: "Is in-clinic or at-home whitening better?", a: "In-clinic whitening is faster and supervised. At-home kits are gradual. We can advise on the right choice for you." },
      { q: "Does whitening damage enamel?", a: "Professionally supervised whitening does not damage enamel when used as directed, though some sensitivity is possible." },
      { q: "Can everyone whiten their teeth?", a: "Not everyone. Gum disease, decay, some stains and restorations affect suitability, so we examine first." },
    ],
    related: ["veneers", "smile-makeover", "dental-check-up-cleaning"], reviewedBy: "dr-s-zeenath",
  }),
  T({
    slug: "veneers", group: "cosmetic", title: "Veneers",
    h1: "Dental veneers in Chennai", keyword: "dental veneers in Chennai",
    promise: "Thin porcelain shells that reshape and brighten the front teeth, designed to look natural.",
    intro: "Dental veneers in Chennai are thin, custom-made porcelain shells bonded to the front of teeth to change their shape, colour or alignment. Our cosmetic team designs veneers with you, so the result suits your face and the way you want to smile.",
    image: "white-smile", imageAlt: "Smile with natural white teeth, dental veneers in Chennai",
    doctors: ["dr-s-zeenath"],
    signs: ["Chipped, worn or uneven front teeth", "Stains that do not respond to whitening", "Small gaps between teeth", "Teeth that are slightly misshapen", "You want a more uniform smile without braces"],
    steps: [
      { title: "Smile consultation", body: "We discuss your goals and what is realistic for your teeth." },
      { title: "Planning", body: "We design the shape and shade, sometimes with a preview or trial." },
      { title: "Preparation", body: "A thin layer of enamel is usually shaped, and a scan or impression is taken." },
      { title: "Bonding", body: "Veneers are checked for fit and colour, then bonded to the teeth." },
    ],
    visits: "Usually 2–3 visits", duration: "60–90 minutes per visit",
    benefits: ["Natural-looking improvement in shape and colour", "Resist everyday staining", "Can address several concerns at once", "Less invasive than crowns for suitable teeth"],
    thingsToKnow: ["Preparation removes a thin layer of enamel and is usually permanent", "Veneers can chip if you bite hard objects", "Teeth grinding may need a night guard", "Veneers may need replacing after many years"],
    faqs: [
      { q: "How long do veneers last?", a: "Many last ten years or more with good care, but this varies with habits such as grinding and diet." },
      { q: "Are veneers permanent?", a: "Preparing teeth for porcelain veneers usually involves removing a thin layer of enamel, so the treatment is considered irreversible." },
      { q: "Do veneers look natural?", a: "A well-planned veneer is designed to match the shade, shape and translucency of natural teeth." },
      { q: "Do veneers hurt?", a: "Preparation is done with numbing where needed. Some sensitivity can occur briefly." },
      { q: "Veneers or whitening: which should I choose?", a: "Whitening lightens natural teeth. Veneers change shape and colour. We can help you decide after examination." },
    ],
    related: ["teeth-whitening", "smile-makeover", "dental-crowns-bridges"], reviewedBy: "dr-s-zeenath",
  }),
  T({
    slug: "smile-makeover", group: "cosmetic", title: "Smile makeover",
    h1: "Smile makeover in Chennai", keyword: "smile makeover in Chennai (incl. tooth jewellery)",
    promise: "A planned combination of treatments to reshape, brighten and rebalance your smile.",
    intro: "A smile makeover in Chennai combines treatments such as whitening, bonding, veneers and alignment into one plan designed around you. Changes can range from subtle to complete. We can also discuss tooth jewellery as a small decorative option.",
    image: "white-smile", imageAlt: "Close-up of a bright smile after a smile makeover in Chennai",
    doctors: ["dr-s-zeenath"],
    signs: ["You are unhappy with more than one thing about your smile", "You want a coordinated plan rather than single fixes", "You have a special event or milestone coming up", "You have worn, chipped or uneven teeth", "You would like to explore tooth jewellery"],
    steps: [
      { title: "Smile consultation", body: "We listen to what you want to change and examine your teeth, gums and bite." },
      { title: "Design", body: "We outline a plan combining suitable treatments and explain options and timing." },
      { title: "Treatment", body: "Treatment is carried out in stages, with health first, then cosmetic steps." },
      { title: "Review and care", body: "We check the result with you and explain how to maintain it." },
    ],
    visits: "Several visits, planned to your case", duration: "Varies from a few weeks to a few months",
    benefits: ["A single, coordinated plan", "Tailored from subtle to complete change", "Can include whitening, bonding, veneers and aligners", "Improves confidence in your smile"],
    thingsToKnow: ["Gum and tooth health come first and may need treatment before cosmetic work", "Some elements, like veneers, are irreversible", "Tooth jewellery is decorative and should be placed professionally", "Timing and cost depend on the treatments chosen"],
    faqs: [
      { q: "What does a smile makeover include?", a: "It depends on your goals. It may combine whitening, bonding, veneers, alignment and gum reshaping." },
      { q: "How long does a smile makeover take?", a: "From a few visits to several months, depending on the treatments involved." },
      { q: "Is tooth jewellery safe?", a: "When placed professionally with dental-grade materials, tooth gems can be a safe decorative option. They are not permanent and can be removed." },
      { q: "Can I see the result before treatment starts?", a: "Where possible, we use planning tools or trial approaches to preview the likely result." },
      { q: "Is a smile makeover only cosmetic?", a: "It often improves function as well, but we always treat any disease first." },
    ],
    related: ["veneers", "teeth-whitening", "invisalign-clear-aligners"], reviewedBy: "dr-s-zeenath",
  }),
  T({
    slug: "tmj-jaw-pain", group: "specialist", title: "TMJ & jaw pain",
    h1: "TMJ and jaw pain treatment in Chennai", keyword: "TMJ and jaw pain treatment in Chennai",
    promise: "Assessment and relief for jaw pain, clicking and grinding.",
    intro: "TMJ and jaw pain treatment in Chennai begins with understanding why your jaw hurts. Problems with the temporomandibular joint can cause pain, clicking, headaches and difficulty opening wide. We assess your jaw and bite and recommend options such as night guards and other supportive care.",
    image: "opg-xray", imageAlt: "Panoramic X-ray of the jaw, used in TMJ and jaw pain treatment in Chennai",
    doctors: ["dr-aravind-sai"],
    signs: ["Jaw pain or tenderness", "Clicking, popping or locking of the jaw", "Headaches or ear-area pain", "Waking up with a tight jaw or worn teeth", "Difficulty opening wide or chewing"],
    steps: [
      { title: "Assessment", body: "We examine the jaw joint, muscles and bite, and review your symptoms." },
      { title: "Imaging if needed", body: "X-ray or other imaging may be used to rule out other causes." },
      { title: "Treatment plan", body: "Options may include a custom night guard, bite assessment and advice on habits and exercises." },
      { title: "Review", body: "We follow up to see how your symptoms are responding." },
    ],
    visits: "A few visits", duration: "30–45 minutes per visit",
    benefits: ["Relief from jaw pain and tension", "Protects teeth from grinding", "A clear explanation of your symptoms", "Non-surgical options first"],
    thingsToKnow: ["Many TMJ problems improve with conservative care", "Stress and grinding habits often play a role", "Night guards help most when worn consistently", "Some cases need referral or further investigation"],
    faqs: [
      { q: "What causes TMJ pain?", a: "Causes include grinding or clenching, injury, arthritis and muscle strain. A proper examination helps find the likely cause." },
      { q: "Is a night guard helpful for jaw pain?", a: "For many people who grind or clench, a custom night guard reduces strain on the jaw and protects teeth." },
      { q: "Will TMJ go away on its own?", a: "Mild symptoms sometimes settle, but persistent or worsening pain should be assessed." },
      { q: "Can dental problems cause jaw pain?", a: "Yes, including bite problems, tooth pain and missing teeth. We check these as part of the assessment." },
      { q: "Is surgery needed for TMJ?", a: "Rarely. Most cases are managed without surgery." },
    ],
    related: ["oral-maxillofacial-surgery", "braces", "dental-check-up-cleaning"], reviewedBy: "dr-aravind-sai",
  }),
  T({
    slug: "sedation-dentistry", group: "specialist", title: "Sedation dentistry",
    h1: "Sedation dentistry in Chennai", keyword: "sedation dentistry in Chennai",
    promise: "Oral conscious sedation to help anxious patients stay relaxed and comfortable.",
    intro: "Sedation dentistry in Chennai helps patients who feel anxious, have a strong gag reflex or need longer treatment. At Alpha Dental Studio, we offer oral conscious sedation: you take a medicine before your appointment and stay awake but deeply relaxed.",
    image: "clinic-room-alt", imageAlt: "Calm dental consultation room, sedation dentistry in Chennai",
    doctors: [],
    signs: ["You feel very anxious about dental visits", "You have a strong gag reflex", "You have a low pain tolerance", "You need long or multiple procedures", "You have avoided the dentist for a long time"],
    steps: [
      { title: "Consultation and health check", body: "We review your medical history and medicines to check sedation is suitable." },
      { title: "Pre-appointment medicine", body: "You take the prescribed sedative as instructed before your visit." },
      { title: "Treatment", body: "You remain awake but relaxed while treatment is carried out and monitored." },
      { title: "Recovery", body: "You rest afterwards and go home with a companion." },
    ],
    visits: "Planned with your treatment", duration: "Depends on the treatment",
    benefits: ["Deep relaxation while staying awake", "Many people remember little of the treatment", "Longer procedures can often be completed in fewer visits", "Helpful for dental fear and gag reflex"],
    thingsToKnow: ["You need someone to take you home and stay with you", "Do not drive or make important decisions for the rest of the day", "Follow fasting and medicine instructions exactly", "Not suitable for everyone, so we assess your health first"],
    faqs: [
      { q: "What is oral conscious sedation?", a: "You take a sedative medicine before treatment and remain awake but deeply relaxed. It is different from general anaesthesia." },
      { q: "Is sedation dentistry safe?", a: "It is generally safe when you are assessed properly and follow instructions. We review your medical history first." },
      { q: "Will I be asleep?", a: "No. You stay awake and able to respond, but feel very relaxed." },
      { q: "Which treatments can be done with sedation?", a: "Extractions, root canals, implants, gum grafting, multiple fillings, complex restorations, cosmetic work and dentures can be done with sedation." },
      { q: "Can I drive after sedation?", a: "No. Arrange for someone to take you home and rest for the day." },
    ],
    related: ["tooth-extraction", "dental-implants", "root-canal-treatment"], reviewedBy: undefined,
  }),
  T({
    slug: "special-needs-dentistry", group: "specialist", title: "Special needs dentistry",
    h1: "Special needs dentistry in Chennai", keyword: "special needs dentistry in Chennai",
    promise: "Compassionate, personalised dental care for patients with special needs and their families.",
    intro: "Special needs dentistry in Chennai means dental care shaped around the individual. At Alpha Dental Studio, we create a supportive, comfortable environment, keep communication open with patients and their families, and build custom hygiene and treatment plans. We also help patients with a severe gag reflex or dental phobia.",
    image: "clinic-room-alt", imageAlt: "Calm dental consultation room for special needs dentistry in Chennai",
    doctors: [],
    signs: ["Routine dental visits have been difficult or stressful", "Your family member needs extra time, patience or a different approach", "You need a custom hygiene and prevention plan", "There is a severe gag reflex or strong dental fear", "You want care coordinated with carers or other health professionals"],
    steps: [
      { title: "Care consultation", body: "We talk with the patient and family about needs, preferences and past experiences." },
      { title: "Personalised comfort menu", body: "We agree on comfort options, such as blankets, neck pillows, music or shows, and refreshments." },
      { title: "Custom treatment plan", body: "A plan is built around the patient, with preventive care first and treatment paced to their comfort." },
      { title: "Ongoing support", body: "We keep in touch with families and carers and coordinate care where needed." },
    ],
    visits: "Planned around the patient", duration: "Varies; we allow extra time",
    benefits: ["Care tailored to individual needs", "Open communication with families and carers", "Gentle methods and relaxation options where suitable", "Support for pain management and emergencies"],
    thingsToKnow: ["Share as much as you can about medical history, medicines and communication preferences", "Short, early visits help build trust", "Sedation options may be discussed where clinically suitable", "Every plan is individual, so we assess before recommending anything"],
    faqs: [
      { q: "What does special needs dentistry include?", a: "Custom hygiene plans, preventive care, specialised oral care, care coordination, custom treatment plans, pain management and emergency dental care." },
      { q: "Can you help with a severe gag reflex?", a: "Yes. We use gentle methods and advanced technologies to reduce triggers, and tailor the approach to make appointments comfortable." },
      { q: "I have a strong fear of the dentist. Can you help?", a: "Yes. We use relaxation techniques, sedation options and open conversation to build trust at your pace." },
      { q: "Can a carer stay with the patient?", a: "Please speak to us when booking so we can plan the visit around the patient's needs." },
      { q: "How do I prepare for the first visit?", a: "Tell us about the patient's needs, medicines and anything that helps them feel calm, so we can prepare in advance." },
    ],
    related: ["sedation-dentistry", "kids-dentistry", "dental-check-up-cleaning"], reviewedBy: undefined,
  }),
  T({
    slug: "digital-dentistry", group: "specialist", title: "Digital dentistry",
    h1: "Digital dentistry and intraoral scanning in Chennai", keyword: "digital dentistry and intraoral scanning in Chennai",
    promise: "Digital X-rays, intraoral cameras and scanning for clearer diagnosis and more precise treatment.",
    intro: "Digital dentistry and intraoral scanning in Chennai replace messy impressions and film X-rays with faster, more detailed technology. At Alpha Dental Studio, we use digital X-rays with reduced radiation, intraoral cameras that let you see your own teeth, and 3D imaging for complex procedures.",
    image: "intraoral-scanner", imageAlt: "Dentist scanning a patient's teeth with an intraoral scanner, digital dentistry in Chennai",
    doctors: [],
    signs: ["You dislike traditional impression material", "You want to see what your dentist sees", "You are planning implants, aligners or crowns", "You need imaging with lower radiation", "You want clearer explanations of your treatment"],
    steps: [
      { title: "Digital imaging", body: "Digital X-rays give instant, detailed images with reduced radiation." },
      { title: "Intraoral camera", body: "A small camera shows you close-up views of your teeth on screen." },
      { title: "Scanning", body: "A scanner records the shape of your teeth digitally for planning and restorations." },
      { title: "Planning", body: "We use the data to plan treatment and explain it with clear visuals." },
    ],
    visits: "Part of your regular visit", duration: "A few minutes",
    benefits: ["Reduced radiation with digital X-rays", "See your own teeth on screen", "More comfortable than traditional impressions", "Supports precise planning for implants and aligners"],
    thingsToKnow: ["Technology supports, but does not replace, a clinical examination", "Not every treatment needs 3D imaging", "Scans are stored securely as part of your record", "Ask us which tools are used for your treatment"],
    faqs: [
      { q: "What is an intraoral scanner?", a: "A small wand that captures a digital 3D model of your teeth, replacing messy impression material." },
      { q: "Are digital X-rays safer?", a: "They use a lower radiation dose than traditional film X-rays." },
      { q: "What is an intraoral camera?", a: "A small camera that shows close-up images of your teeth so you can see what your dentist sees." },
      { q: "When is 3D imaging used?", a: "For more complex procedures such as implant planning, where detail about bone and nerves matters." },
      { q: "Is digital dentistry more expensive?", a: "Costs depend on the treatment. We explain any imaging charges before we start." },
    ],
    related: ["dental-implants", "invisalign-clear-aligners", "dental-crowns-bridges"], reviewedBy: undefined,
  }),
];

export const getTreatment = (slug: string) => treatments.find((t) => t.slug === slug);
export const treatmentsByGroup = (groupId: string) => treatments.filter((t) => t.group === groupId);
export const groupOf = (t: Treatment) => treatmentGroups.find((g) => g.id === t.group)!;
export type { Doctor };
